task: "DATASET"
output_dir: "src/dataset/data"
translation_model:
  name: "Unbabel/Tower-Plus-72B"
  provider: "local"
judge_model:
  name: "Unbabel/Tower-Plus-72B"
  provider: "local"
task_config:
  dataset: 
    name: "google/wmt24pp"
    subset: ["en-uk_UA"]
    split: ["train"]
    n_entries: 700
  target_language: "Ukrainian"
  method: "USI" # SC, USI, TRANK, BoN
  temperature_translator: 0.7
  temperature_judge: 0.1
  max_workers: False
  num_workers: 30
  n_samples: 1
  fields: ["source"]
  agent_check: False
  few_shot: False
  multi_prompt: True
  save_to_hf: False
  prompt_files: ["example_base_1.txt", "example_base_2.txt", "example_base_3.txt", "ukrainian/example_base_1_ukr.txt", "ukrainian/example_base_2_ukr.txt"]

  
