task: "DATASET"
output_dir: "src/benchmark/data"
translation_model:
  name: "gemini-2.5-flash-preview-04-17"
  provider: "google"
judge_model:
  name: "gemini-2.5-flash-preview-04-17"
  provider: "google"
task_config:
  dataset: 
    name: "THUDM/LongBench"
    subset: ["2wikimqa", "gov_report", "multi_news", "multifieldqa_en", "musique", "narrativeqa", "passage_retrieval_en", "qasper", "samsum"]
    split: ["test"]
    n_entries: 10
  target_language: "Ukrainian"
  method: "SC" # SC, USI, TRANK, BoN
  temperature_translator: 0.3
  temperature_judge: 0.1
  max_workers: True
  num_workers: 1
  n_samples: 1
  fields: ["input", "context", "answers"]
  agent_check: False
  few_shot: False
  multi_prompt: False
  save_to_hf: True
  prompt_files: ["example_base_1.txt", "example_base_2.txt", "ukrainian/example_base_1_ukr.txt"]

