task: "BENCHMARK"
output_dir: "src/benchmark/data"
translation_model:
  name: "gpt-4o-2024-11-20"
  provider: "openai"
  args: {
    reasoning_level: "low"
  }
judge_model:
  name: "gpt-4o-2024-11-20"
  provider: "openai"
  args: {
    reasoning_level: "low"
  }
task_config:
  benchmark: 
    name: "mandarjoshi/trivia_qa"
    subset: ["rc.nocontext"]
    split: ["validation"]
  target_language: "Ukrainian"
  method: "USI" # SC, USI, TRANK, BoN
  max_workers: True
  num_workers: 1
  n_samples: 1
  question_fields: ["question"]
  answer_fields: ["answer.aliases"]
  agent_check: False
  few_shot: False
  multi_prompt: True
  prompt_files: ["trivia_qa/trivia_qa_base_1.txt", "trivia_qa/trivia_qa_base_2.txt", "trivia_qa/trivia_qa_base_2_ukr.txt"]

