task: "DATASET"
output_dir: "src/dataset/data"
translation_model:
  name: "google/gemini-2.0-flash-001"
  provider: "openrouter"
judge_model:
  name: "google/gemini-2.0-flash-001"
  provider: "openrouter"
task_config:
  dataset: 
    name: "gsarti/flores_101"
    subset: ["eng"]
    split: ["devtest"]
  target_language: "Ukrainian"
  method: "USI" # SC, USI, TRANK, BoN
  max_workers: False
  num_workers: 70
  n_samples: 5
  fields: ["sentence"]
  agent_check: False
  few_shot: False
  multi_prompt: True
  prompt_files: ["example_base_1.txt", "example_base_2.txt", "example_base_3.txt", "ukrainian/example_base_1_ukr.txt", "ukrainian/example_base_2_ukr.txt"]

  
